### PR TITLE
Reviews from Pete and Nasim

### PR DESCRIPTION
**Pull request by CallumCheng**
New pull request for reviewers. Just need to add comments etc. no need to merge. Cheers

### CODE REVIEW

**Comment by Lmnofuktranzgettempeterdunlap** [comment]
Yeah cheers

**Comment by Default-Qube** [comment]
> Yeah cheers

Who's this cunt?

**Comment by CallumCheng** [comment]
Wet wipe

**Comment by ghost** [comment]
> Wet wipe

Who the fuck is that guy commenting (the one who said "Yeah cheers")?! I've closed all of my open pull requests to stop the cunt doing it again.

**Pull request closed without merging**
